import type { CoachListing, CoachReview, NewsItem, SessionPost } from "@/lib/types";

function enrichCoach(
  base: Omit<
    CoachListing,
    | "rating"
    | "reviewCount"
    | "languages"
    | "isVirtual"
    | "badges"
    | "price45"
    | "price60"
    | "price90"
  > &
    Partial<Pick<CoachListing, "rating" | "reviewCount" | "languages" | "isVirtual" | "badges" | "greenTravel">>,
): CoachListing {
  const hourly = base.hourlyRateUsd;
  return {
    ...base,
    rating: base.rating ?? 4.7 + (base.trustScore % 3) * 0.1,
    reviewCount: base.reviewCount ?? 12 + (base.trustScore % 40),
    languages: base.languages ?? ["English"],
    isVirtual: base.isVirtual ?? false,
    badges: base.badges ?? ["responsive", "trusted_parents"],
    price45: Math.round(hourly * 0.85),
    price60: hourly,
    price90: Math.round(hourly * 1.35),
  };
}

const RAW_COACHES: Parameters<typeof enrichCoach>[0][] = [
  {
    id: "coach-priya",
    name: "Priya Sharma",
    avatarUrl: "https://images.unsplash.com/photo-1573496773905-f5b598e8b738?w=400&h=400&fit=crop&q=80",
    sport: "Cricket",
    location: "Mumbai, IN",
    levelTags: ["Beginner", "Club", "U-16"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: true,
    trustScore: 88,
    bio: "Former state-level batter coaching girls with culturally sensitive drills, modesty-friendly sessions, and Hindi/English instruction.",
    experienceYears: 11,
    certifications: ["BCCI Level B", "SafeSport", "Background Verified"],
    hourlyRateUsd: 42,
    groupRateUsd: 18,
    languages: ["English", "Hindi", "Gujarati"],
    badges: ["preferred_girls", "ten_girls", "trusted_parents", "responsive"],
    greenTravel: true,
  },
  {
    id: "coach-maya",
    name: "Maya Chen",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&q=80",
    sport: "Basketball",
    location: "Bangalore, IN",
    levelTags: ["Intermediate", "High School"],
    sessionTypes: ["private"],
    isFemaleCoach: true,
    trustScore: 82,
    bio: "Former D1 guard helping athletes sharpen footwork, decision-making under pressure, and leadership on court.",
    experienceYears: 12,
    certifications: ["GBB Gold Licensed", "Mental Skills Foundations"],
    hourlyRateUsd: 55,
    languages: ["English", "Tamil"],
    badges: ["preferred_girls", "responsive"],
  },
  {
    id: "coach-ananya",
    name: "Ananya Iyer",
    avatarUrl: "https://images.unsplash.com/photo-1542596594-649edbc13630?w=400&h=400&fit=crop&q=80",
    sport: "Badminton",
    location: "Chennai, IN",
    levelTags: ["Beginner", "Club"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: true,
    trustScore: 76,
    bio: "National junior medalist specializing in footwork, smash technique, and building confidence after setbacks.",
    experienceYears: 8,
    certifications: ["BWF Level 1", "Youth Safety"],
    hourlyRateUsd: 38,
    groupRateUsd: 15,
    languages: ["English", "Tamil"],
    isVirtual: true,
    badges: ["ten_girls", "responsive"],
  },
  {
    id: "coach-alex",
    name: "Alex Rivera",
    avatarUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop&q=80",
    sport: "Football",
    location: "Delhi, IN",
    levelTags: ["Beginner", "Club"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: false,
    trustScore: 71,
    bio: "AFC-licensed trainer focused on confidence, tactical basics, and parent-friendly progress updates.",
    experienceYears: 9,
    certifications: ["AFC C License", "SafeSport", "CPR/AED"],
    hourlyRateUsd: 48,
    groupRateUsd: 22,
    languages: ["English", "Hindi"],
  },
  {
    id: "coach-riley",
    name: "Riley Thompson",
    avatarUrl: "https://images.unsplash.com/photo-1573497161161-c3e737856e74?w=400&h=400&fit=crop&q=80",
    sport: "Tennis",
    location: "Hyderabad, IN",
    levelTags: ["Middle School", "High School"],
    sessionTypes: ["private"],
    isFemaleCoach: true,
    trustScore: 91,
    bio: "Backhand specialist with respectful communication modeled for teammates. Coach Duo available for first sessions.",
    experienceYears: 11,
    certifications: ["PTR Professional", "First Aid"],
    hourlyRateUsd: 62,
    languages: ["English", "Hindi"],
    badges: ["preferred_girls", "trusted_parents", "ten_girls"],
  },
  {
    id: "coach-jordan",
    name: "Jordan Malik",
    avatarUrl: "https://images.unsplash.com/photo-1573497491208-87b9295e063c?w=400&h=400&fit=crop&q=80",
    sport: "Track & Field",
    location: "Pune, IN",
    levelTags: ["Beginner", "Club"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: false,
    trustScore: 58,
    bio: "Sprints & hurdles fundamentals with runway mechanics and weekly progress snapshots for parents.",
    experienceYears: 7,
    certifications: ["USATF Level 1", "Youth Athletics Safety"],
    hourlyRateUsd: 40,
    groupRateUsd: 16,
    greenTravel: true,
    badges: ["green_travel", "responsive"],
  },
  {
    id: "coach-nadia",
    name: "Nadia Koh",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&q=80",
    sport: "Badminton",
    location: "Singapore, SG",
    levelTags: ["Beginner", "Club", "U-16"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: true,
    trustScore: 85,
    bio: "Former national junior medalist building footwork, smash technique, and inclusive group pods across Singapore.",
    experienceYears: 10,
    certifications: ["BWF Level 1", "SafeSport"],
    hourlyRateUsd: 52,
    groupRateUsd: 20,
    languages: ["English", "Mandarin"],
    badges: ["preferred_girls", "trusted_parents", "responsive"],
  },
  {
    id: "coach-wei",
    name: "Wei Lin Tan",
    avatarUrl: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&h=400&fit=crop&q=80",
    sport: "Swimming",
    location: "Singapore, SG",
    levelTags: ["Beginner", "Club"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: false,
    trustScore: 79,
    bio: "Stroke technique and endurance blocks at public pools — bilingual coaching for school teams.",
    experienceYears: 9,
    certifications: ["SwimSafer Coach", "AUSTSWIM"],
    hourlyRateUsd: 48,
    groupRateUsd: 18,
    languages: ["English", "Mandarin"],
    greenTravel: true,
  },
  {
    id: "coach-sarah",
    name: "Sarah Okafor",
    avatarUrl: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&h=400&fit=crop&q=80",
    sport: "Football",
    location: "London, UK",
    levelTags: ["Beginner", "Club", "High School"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: true,
    trustScore: 90,
    bio: "FA-qualified coach running girls-only pods in North London with emphasis on first touch and game IQ.",
    experienceYears: 13,
    certifications: ["FA Level 2", "DBS Checked", "SafeSport"],
    hourlyRateUsd: 58,
    groupRateUsd: 22,
    languages: ["English"],
    badges: ["preferred_girls", "ten_girls", "trusted_parents"],
  },
  {
    id: "coach-emma",
    name: "Emma Hughes",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&q=80",
    sport: "Tennis",
    location: "Manchester, UK",
    levelTags: ["Intermediate", "High School"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: true,
    trustScore: 84,
    bio: "LTA coach for juniors — serve routines, match play, and peer pods for club-level athletes.",
    experienceYears: 10,
    certifications: ["LTA Level 3", "First Aid"],
    hourlyRateUsd: 54,
    groupRateUsd: 19,
    languages: ["English"],
    badges: ["responsive", "trusted_parents"],
  },
  {
    id: "coach-taylor",
    name: "Taylor Brooks",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&q=80",
    sport: "Basketball",
    location: "Austin, US",
    levelTags: ["Club", "High School"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: true,
    trustScore: 86,
    bio: "Former college guard — spacing, off-ball movement, and high-energy peer runs in Austin.",
    experienceYears: 11,
    certifications: ["USA Basketball Gold", "SafeSport"],
    hourlyRateUsd: 65,
    groupRateUsd: 24,
    languages: ["English", "Spanish"],
    badges: ["preferred_girls", "responsive"],
  },
  {
    id: "coach-jess",
    name: "Jess Martinez",
    avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&q=80",
    sport: "Football",
    location: "New York, US",
    levelTags: ["Beginner", "Club", "Middle School"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: true,
    trustScore: 88,
    bio: "USSF-licensed trainer for NYC youth — small-sided games, confidence, and Manhattan/Brooklyn pods.",
    experienceYears: 12,
    certifications: ["USSF C License", "SafeSport"],
    hourlyRateUsd: 72,
    groupRateUsd: 26,
    languages: ["English", "Spanish"],
    badges: ["preferred_girls", "ten_girls", "trusted_parents"],
  },
  {
    id: "coach-kai",
    name: "Kai Nakamura",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&q=80",
    sport: "Volleyball",
    location: "Los Angeles, US",
    levelTags: ["Intermediate", "Club"],
    sessionTypes: ["private", "group"],
    isFemaleCoach: false,
    trustScore: 74,
    bio: "Beach and indoor fundamentals — setting clinics and peer pods across LA county.",
    experienceYears: 8,
    certifications: ["USAV CAP I", "SafeSport"],
    hourlyRateUsd: 60,
    groupRateUsd: 22,
    languages: ["English", "Japanese"],
    isVirtual: true,
    badges: ["responsive"],
  },
];

export const PLACEHOLDER_COACHES: CoachListing[] = RAW_COACHES.map((c) => enrichCoach(c));

export const PLACEHOLDER_SESSIONS: SessionPost[] = [
  {
    id: "sess-cricket-mon",
    coachId: "coach-priya",
    title: "Cover drive clinic + footwork ladder",
    sport: "Cricket",
    level: "Club",
    location: "Mumbai Sports Club",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2 + 1000 * 60 * 60 * 17).toISOString(),
    durationMin: 75,
    priceUsd: 18,
    spotsTotal: 10,
    spotsLeft: 4,
  },
  {
    id: "sess-hoops-wed",
    coachId: "coach-maya",
    title: "Ball handling laboratory",
    sport: "Basketball",
    level: "Intermediate",
    location: "Virtual · Zoom",
    sessionType: "private",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4 + 1000 * 60 * 60 * 16).toISOString(),
    durationMin: 60,
    priceUsd: 55,
  },
  {
    id: "sess-cricket-peer",
    coachId: "coach-priya",
    title: "Club net session — peer pod",
    sport: "Cricket",
    level: "Club",
    location: "Mumbai Sports Club",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 6 + 1000 * 60 * 60 * 17).toISOString(),
    durationMin: 90,
    priceUsd: 18,
    spotsTotal: 8,
    spotsLeft: 5,
  },
  {
    id: "sess-badminton-peer",
    coachId: "coach-ananya",
    title: "Doubles footwork with peers",
    sport: "Badminton",
    level: "Club",
    location: "Chennai, IN",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5 + 1000 * 60 * 60 * 18).toISOString(),
    durationMin: 75,
    priceUsd: 16,
    spotsTotal: 6,
    spotsLeft: 3,
  },
  {
    id: "sess-badminton-sg",
    coachId: "coach-nadia",
    title: "Club doubles pod — peers welcome",
    sport: "Badminton",
    level: "Club",
    location: "Singapore Sports Hub",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 10).toISOString(),
    durationMin: 90,
    priceUsd: 20,
    spotsTotal: 10,
    spotsLeft: 6,
  },
  {
    id: "sess-swim-sg",
    coachId: "coach-wei",
    title: "Freestyle peer lane",
    sport: "Swimming",
    level: "Club",
    location: "Singapore, SG",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7 + 1000 * 60 * 60 * 7).toISOString(),
    durationMin: 60,
    priceUsd: 18,
    spotsTotal: 8,
    spotsLeft: 4,
  },
  {
    id: "sess-football-london",
    coachId: "coach-sarah",
    title: "Sunday small-sided peer pod",
    sport: "Football",
    level: "Club",
    location: "London, UK",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4 + 1000 * 60 * 60 * 11).toISOString(),
    durationMin: 75,
    priceUsd: 22,
    spotsTotal: 12,
    spotsLeft: 7,
  },
  {
    id: "sess-tennis-manchester",
    coachId: "coach-emma",
    title: "Doubles rotation — club level",
    sport: "Tennis",
    level: "Club",
    location: "Manchester, UK",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 8 + 1000 * 60 * 60 * 15).toISOString(),
    durationMin: 90,
    priceUsd: 19,
    spotsTotal: 8,
    spotsLeft: 3,
  },
  {
    id: "sess-hoops-austin",
    coachId: "coach-taylor",
    title: "Pick-up run with peers",
    sport: "Basketball",
    level: "Club",
    location: "Austin, US",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5 + 1000 * 60 * 60 * 18).toISOString(),
    durationMin: 90,
    priceUsd: 24,
    spotsTotal: 10,
    spotsLeft: 5,
  },
  {
    id: "sess-football-nyc",
    coachId: "coach-jess",
    title: "NYC club scrimmage pod",
    sport: "Football",
    level: "Club",
    location: "New York, US",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 6 + 1000 * 60 * 60 * 17).toISOString(),
    durationMin: 75,
    priceUsd: 26,
    spotsTotal: 14,
    spotsLeft: 8,
  },
  {
    id: "sess-volleyball-la",
    coachId: "coach-kai",
    title: "Beach skills peer session",
    sport: "Volleyball",
    level: "Club",
    location: "Los Angeles, US",
    sessionType: "group",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 9 + 1000 * 60 * 60 * 16).toISOString(),
    durationMin: 80,
    priceUsd: 22,
    spotsTotal: 8,
    spotsLeft: 4,
  },
];

export const DAILY_QUOTES = [
  { text: "You belong on this pitch. Every rep is proof.", author: "ShePlays" },
  { text: "Courage is showing up when your legs are tired.", author: "Mentor Network" },
  { text: "Strong girls lift each other — on and off the field.", author: "Community" },
];

export const PLACEHOLDER_NEWS: NewsItem[] = [
  {
    id: "news-1",
    title: "India U-16 girls cricket camp opens scholarships",
    sport: "Cricket",
    excerpt: "Regional trials in Mumbai and Delhi — applications close June 30.",
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    kind: "event",
  },
  {
    id: "news-2",
    title: "Priya just completed her 20th session! 🎉",
    sport: "Community",
    excerpt: "Consistency Star badge unlocked — keep shining!",
    publishedAt: new Date(Date.now() - 172800000).toISOString(),
    kind: "community",
  },
  {
    id: "news-3",
    title: "Mental skills workshop for young athletes",
    sport: "All",
    excerpt: "Free virtual session with sports psychologists this Saturday.",
    publishedAt: new Date(Date.now() - 259200000).toISOString(),
    kind: "news",
  },
];

export const PLACEHOLDER_REVIEWS: CoachReview[] = [
  {
    id: "rev-1",
    coachId: "coach-priya",
    author: "Parent · Meera K.",
    role: "parent",
    rating: 5,
    body: "Priya is patient, professional, and my daughter finally loves cricket again.",
    createdAt: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: "rev-2",
    coachId: "coach-priya",
    author: "Anika, 14",
    role: "student",
    rating: 5,
    body: "She explains things in Hindi when I need it. Best coach ever!",
    createdAt: new Date(Date.now() - 1209600000).toISOString(),
  },
  {
    id: "rev-3",
    coachId: "coach-maya",
    author: "Parent · Raj P.",
    role: "parent",
    rating: 4,
    body: "Great virtual sessions. Would love more weekend slots.",
    createdAt: new Date(Date.now() - 864000000).toISOString(),
  },
];

export const DEFAULT_BADGES = [
  { id: "spin-queen", emoji: "🎾", title: "Spin Queen" },
  { id: "ten-hero", emoji: "🏆", title: "10-Session Hero" },
  { id: "comeback", emoji: "💪", title: "Comeback Kid" },
  { id: "hattrick", emoji: "🏏", title: "Hat-Trick Hero" },
  { id: "consistency", emoji: "⭐", title: "Consistency Star" },
];

export type MentorCard = {
  id: string;
  name: string;
  sport: string;
  bio: string;
  avatarUrl: string;
  personality: "calm" | "high-energy" | "motivational";
  languages: string[];
  matchScore?: number;
};

export const PLACEHOLDER_MENTORS: MentorCard[] = [
  {
    id: "mentor-lila",
    name: "Lila Navarro",
    sport: "Cricket",
    bio: "Pro batter sharing how she balances school, friendships, and high-performance training.",
    avatarUrl: "https://images.unsplash.com/photo-1573497491208-87b9295e063c?w=600&h=400&fit=crop&q=80",
    personality: "motivational",
    languages: ["English", "Hindi"],
    matchScore: 94,
  },
  {
    id: "mentor-keisha",
    name: "Keisha Morgan",
    sport: "Track & Field",
    bio: "Sprint specialist focused on nerves before big meets and building resilient routines.",
    avatarUrl: "https://images.unsplash.com/photo-1573497161161-c3e737856e74?w=600&h=400&fit=crop&q=80",
    personality: "high-energy",
    languages: ["English"],
    matchScore: 87,
  },
  {
    id: "mentor-aida",
    name: "Aida Mensah",
    sport: "Swimming",
    bio: "Open-water athlete mentoring girls on body confidence, injury recovery, and cultural expectations.",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=400&fit=crop&q=80",
    personality: "calm",
    languages: ["English", "Tamil"],
    matchScore: 91,
  },
];

export type MentorVideoCard = {
  id: string;
  title: string;
  mentorName: string;
  thumbUrl: string;
  topic: string;
};

export const PLACEHOLDER_MENTOR_VIDEOS: MentorVideoCard[] = [
  {
    id: "vid-01",
    title: "Owning your warmup like a captain",
    mentorName: "Lila Navarro",
    thumbUrl: "https://images.unsplash.com/photo-1560253029-252a372291b9?w=800&h=450&fit=crop&q=80",
    topic: "Leadership",
  },
  {
    id: "vid-02",
    title: "From nervous freshman to fearless starter",
    mentorName: "Keisha Morgan",
    thumbUrl: "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?w=800&h=450&fit=crop&q=80",
    topic: "Overcoming failure",
  },
  {
    id: "vid-03",
    title: "What I wish I knew after my ACL tear",
    mentorName: "Aida Mensah",
    thumbUrl: "https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf?w=800&h=450&fit=crop&q=80",
    topic: "Injury recovery",
  },
  {
    id: "vid-04",
    title: "Balancing board exams and nationals",
    mentorName: "Lila Navarro",
    thumbUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=450&fit=crop&q=80",
    topic: "Academics & sport",
  },
];

export function quoteOfTheDay(): (typeof DAILY_QUOTES)[0] {
  const day = Math.floor(Date.now() / 86400000);
  return DAILY_QUOTES[day % DAILY_QUOTES.length]!;
}
